#pragma once

#include <dpp/discord.h>

namespace dpp {

struct embed_footer {
	std::string text;
	std::string icon_url;
	std::string proxy_url;
};

struct embed_image {
	std::string url;
	std::string proxy_url;
	std::string height;
	std::string width;
};

struct embed_thumbnail : public embed_image {
};

struct embed_video : public embed_image {
};

struct embed_provider {
	std::string name;
	std::string url;
};

struct embed_author {
	std::string name;
	std::string url;
	std::string icon_url;
	std::string proxy_icon_url;
};

struct embed_field {
	std::string name;
	std::string value;
	std::string is_inline;
};

struct embed {
	std::string			title;			/* Optional: title of embed */
	std::string			type;			/* Optional: type of embed (always "rich" for webhook embeds) */
	std::string			description;		/* Optional: description of embed */
	std::string			url;			/* Optional: url of embed */
	time_t				timestamp;		/* Optional: timestamp of embed content */
	uint32_t			color;			/* Optional: color code of the embed */
	embed_footer*			footer = nullptr;	/* Optional: footer information */
	embed_image*			image = nullptr;	/* Optional: image information */
	embed_thumbnail*		thumbnail = nullptr;	/* Optional: thumbnail information */
	embed_video*			video = nullptr;	/* Optional: video information */
	embed_provider*			provider = nullptr;	/* Optional: provider information */
	embed_author*			author = nullptr;	/* Optional: author information */
	std::vector<embed_field>	fields;			/* Optional: fields information */
};

struct reaction {
	uint32_t count;
	bool me;
	snowflake emoji_id;
};

struct message {
	snowflake       id;				/* id of the message */
	snowflake       channel_id;			/* id of the channel the message was sent in */
	snowflake       guild_id;			/* Optional: id of the guild the message was sent in */
	user*		author;				/* the author of this message (not guaranteed to be a valid user, see below) */
	guild_member*	member;				/* Optional: member properties for this message's author */
	std::string	content;			/* contents of the message */
	time_t		sent;				/* when this message was sent */
	time_t		edited;				/* when this message was edited (or null if never) (may be empty) */
	bool		tts;				/* whether this was a TTS message */
	bool   		mention_everyone;		/* whether this message mentions everyone */
	user*		mentions;			/* users specifically mentioned in the message */
	role*		mention_roles;			/* roles specifically mentioned in this message */
	std::vector<snowflake> mention_channels;	/* Optional: channels specifically mentioned in this message */
	std::vector<const unsigned char*> attachments;	/* any attached files */
	std::vector<embed> embeds;			/* any embedded content */
	std::vector<reaction> reactions;		/* Optional: reactions to the message */
	std::string	nonce;				/* Optional: used for validating a message was sent */
	bool		pinned;				/* whether this message is pinned */
	snowflake	webhook_id;			/* Optional: if the message is generated by */
};

};
