name: clang-format
on: [push, pull_request]
jobs:
  formatting-check:
    name: Format check
    runs-on: ubuntu-latest
    strategy:
          matrix:
            path:
              - 'src'
              - 'include'
              - exclude: '(fmt|nlohmann)' 
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      with:
        clang-format-version: '13'
