name: clang-format
on: [push, pull_request]
jobs:
  formatting-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      with:
        clang-format-version: '13'
