name: Prepare release for VCPKG

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to package'
        required: true

permissions:
  contents: read

jobs:
  Collect-Vcpkg-Info:
    permissions:
      contents: write # Allow the creation of a release.
    runs-on: ubuntu-latest
    steps:
         - name: Harden Runner
           uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
           with:
             egress-policy: audit

         - name: Setup PHP
           uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
           with:
             php-version: '8.1'

         - name: Checkout D++
           uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
           with:
             submodules: recursive

         - name: Update vcpkg and install other dependencies
           run: sudo apt-get update &&
                sudo apt-get install nasm linux-headers-$(uname -r) &&
                cd /usr/local/share/vcpkg &&
                sudo ./bootstrap-vcpkg.sh &&
                sudo git stash &&
                sudo git pull &&
                sudo vcpkg update

         - name: Run vcpkg release builder
           run: git fetch -avt &&
                cd buildtools &&
                php make_vcpkg.php "${{ github.repository_owner }}" "${{ secrets.PERSONAL_ACCESS_TOKEN }}" "${{ inputs.tag }}"
