name: Docs Full Rebuild (dpp.dev)
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    permissions:
      contents: write # Needs to be able to write to the repo.
    name: Rebuild all Documentation
    runs-on: ubuntu-24.04

    concurrency: 
      group: docs-deployment
      cancel-in-progress: true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: '8.3'

      - name: Checkout D++
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Generate Docs
        run: cd docpages && php makedocs-gh.php rebuild-old
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
