name: Close master-targeted PRs
on:
  pull_request_target:
    types: [opened]
    branches:
      - 'master'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@9c18513d320d7b2c7185fb93396d0c664d5d8448 # v3.1.2
      with:
        comment: "Thank you for your contribution, but PRs must be raised against the `dev` branch. Please log your issue against the `dev` branch not `master`. You can also retarget this pull request, then reopen it."

